version: "3.3"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: loopsDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/data
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - "db"
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/loopsDB
      - DATA_PATH='/data/models/data/
volumes:
  postgres_data:
