version: "3.1"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: loopsDB
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/loopsDB
