version: "3.3"

services:
  db:
    image: postgres
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: loopsDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/data
  web:
    build: .
    container_name: web
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/loopsDB
      - DATA_PATH='/data/models/data/
  react:
    build: ./client
    container_name: react
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - PORT=5000

volumes:
  postgres_data:
